# Generated by Django 5.1.6 on 2025-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djchat', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Uname',
            field=models.CharField(default='NaN', max_length=1000),
        ),
    ]
