# Generated by Django 5.1.6 on 2025-02-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djchat', '0005_alter_feedback_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Uname',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
